### ISSUE TITLE
Handler - Committer error when committing large blob file

### ISSUE THREAD

**Issue by lawrencegripper** [lawrencegripper/ion#133]
It looks like the way the handler talks to blob storage causes an issue when uploading a large file. 

Repro: download http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_surround.avi and try and commit it. 

```
time="2018-07-05T09:31:27Z" level=debug msg="using default base directory "
time="2018-07-05T09:31:27Z" level=info msg="committing module's environment to the data plane" correlationID=8d882028-55af-45b0-840f-50e095c37b96 eventID=e24fff88-64e9-4876-87e8-e0d366067c9b name=downloader timestamp="2018-07-05 09:31:27.10669575 +0000 UTC m=+0.200178820"
time="2018-07-05T09:31:27Z" level=info msg="cleaning up handler" correlationID=8d882028-55af-45b0-840f-50e095c37b96 eventID=e24fff88-64e9-4876-87e8-e0d366067c9b name=downloader timestamp="2018-07-05 09:31:27.734847585 +0000 UTC m=+0.828330755"
panic: error during commit error committing blob data: failed to commit blob: storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:e1272285-d01e-0118-3f42-14fe1d000000
Time:2018-07-05T09:31:27.6868587Z, RequestInitiated=Thu, 05 Jul 2018 09:31:26 GMT, RequestId=e1272285-d01e-0118-3f42-14fe1d000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=

goroutine 1 [running]:
github.com/lawrencegripper/ion/internal/app/handler.Run(0x7ffe59318e44, 0x6, 0x988b3f, 0x2, 0xc420062640, 0x7ffe59318d57, 0xf, 0xc420062680, 0xc4200626c0, 0xc42007e960, ...)
	/go/src/github.com/lawrencegripper/ion/internal/app/handler/run.go:97 +0xa18
main.NewStartCommand.func2(0xc42016c000, 0xc4200b6b00, 0x0, 0x16)
	/go/src/github.com/lawrencegripper/ion/cmd/handler/start.go:64 +0x9d
github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra.(*Command).execute(0xc42016c000, 0xc4200b6840, 0x16, 0x16, 0xc42016c000, 0xc4200b6840)
	/go/src/github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42009fb80, 0xc42009fb80, 0xc42016c280, 0xc42016c000)
	/go/src/github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra/command.go:846 +0x30a
github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42009fb80, 0x8c9580, 0xc420070058)
	/go/src/github.com/lawrencegripper/ion/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/go/src/github.com/lawrencegripper/ion/cmd/handler/main.go:10 +0x27
```

**Comment by lawrencegripper** [comment]
Looks like this should be an easy one to move to the new calling method which it recommends to avoid the 256MB limit

```
// CreateBlockBlobFromReader initializes a block blob using data from
// reader. Size must be the number of bytes read from reader. To
// create an empty blob, use size==0 and reader==nil.
//
// Any headers set in blob.Properties or metadata in blob.Metadata
// will be set on the blob.
//
// The API rejects requests with size > 256 MiB (but this limit is not
// checked by the SDK). To write a larger blob, use CreateBlockBlob,
// PutBlock, and PutBlockList.
//
// To create a blob from scratch, call container.GetBlobReference() to
// get an empty blob, fill in blob.Properties and blob.Metadata as
// appropriate then call this method.
```

**Comment by jjcollinge** [comment]
Done in #162
